import React, { useState } from "react";
import {
  Accordion,
  Card,
  Collapse,
  Container,
  Row,
  Col,
} from "react-bootstrap";
import { BiPlusMedical } from "react-icons/bi";
import { FaMinus } from "react-icons/fa";
import "bootstrap/dist/css/bootstrap.min.css";

const FAQ = () => {
  const [openAccordions, setOpenAccordions] = useState([]);

  const toggleAccordion = (index) => {
    const updatedAccordions = [...openAccordions];
    updatedAccordions[index] = !updatedAccordions[index];
    setOpenAccordions(updatedAccordions);
  };

  const accordionData = [
    {
      question: "How does Aniquest work?",
      answer:
        "Hello! I am the content. Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti eius nobis laboriosam totam minus, veritatis ipsum, sed dignissimos, numquam aspernatur inventore autem? Recusandae, veritatis enim sequi debitis neque commodi tempora atque? Quibusdam minima similique quidem id corrupti voluptatibus voluptatum fugit, officia alias tempora maxime omnis nulla veritatis ipsum temporibus amet.",
    },
    {
      question: "What text do you generate from Aniquest?",
      answer:
        "Awesome text generated. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt nam laborum aperiam veritatis eum ex vel fugiat quis impedit numquam.",
    },
    {
      question: "How does AI aniquest work",
      answer:
        "Excellently work. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt nam laborum aperiam veritatis eum ex vel fugiat quis impedit numquam.",
    },
    {
      question: "Can I try aniquest for free",
      answer:
        "Excellently work. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt nam laborum aperiam veritatis eum ex vel fugiat quis impedit numquam.",
    },
    {
      question: "Can AI wrote stories or post of 100+ words",
      answer:
        "Excellently work. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt nam laborum aperiam veritatis eum ex vel fugiat quis impedit numquam.",
    },
    {
      question: "Is content generated by AI original ",
      answer:
        "Excellently work. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt nam laborum aperiam veritatis eum ex vel fugiat quis impedit numquam.",
    },
    {
      question: "How can I make the AI check my texts?",
      answer:
        "Excellently work. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt nam laborum aperiam veritatis eum ex vel fugiat quis impedit numquam.",
    },
    // Add more accordion items as needed
  ];
  return (
    <>
      <div className="faq-spacing text-center">
        <h2 className="fw-bold  frequently-asked">
          Frequently Asked
          <br /> Questions
        </h2>
      </div>
      <div>
        <Container>
          <Row className="d-flex justify-content-center">
            <Col lg={10}>
              <Accordion className="accord-spacing">
                {accordionData.map((accordion, index) => (
                  <Card className="accordian-card mb-3" key={index}>
                    <Card.Header className="accordion-header">
                      <Row>
                        <Col xs={10}>
                          <span className="how-work d-flex align-items-center h-100">
                            {accordion.question}
                          </span>
                        </Col>
                        <Col xs={2} className="d-flex justify-content-end">
                          {openAccordions[index] ? (
                            <div className="both-icon-color d-flex justify-content-center align-items-center">
                              <FaMinus
                                size={20}
                                onClick={() => toggleAccordion(index)}
                              />
                            </div>
                          ) : (
                            <div className="both-icon-color d-flex justify-content-center align-items-center">
                              <BiPlusMedical
                                size={20}
                                onClick={() => toggleAccordion(index)}
                              />
                            </div>
                          )}
                        </Col>
                      </Row>
                    </Card.Header>
                    <Collapse in={openAccordions[index]} timeout={3000}>
                      <Card.Body className="accordian-answer-size">{accordion.answer}</Card.Body>
                    </Collapse>
                  </Card>
                ))}
              </Accordion>
            </Col>
          </Row>
        </Container>
      </div>
    </>
  );
};

export default FAQ;
